### ISSUE TITLE
how to compile this? 

### ISSUE THREAD

**Issue by yanxiyue** [cgreche/open-carom3d-server#1]
Is this source code complete? and how do I compile it?

**Comment by cgreche** [comment]
Hello, my friend.

It's a CMake C++ project, just use an ordinary compile which supports a CMake project.

I've updated the README file. Would you read it, please?

**Comment by yanxiyue** [comment]
> Hello, my friend.
> 
> The project is in very early phase. It's in a playable phase, though. You can enjoy some matches with friends already :)
> 
> It's a CMake C++ project, just use an ordinary compile which supports a CMake project.
> 
> Build from dev branch, there are some notable bugs fixed.
> 
> I've updated the README file. Would you read it, please?

thanks a lot.  I will have a try. good job~~~

**Comment by yanxiyue** [comment]
> > Hello, my friend.
> > The project is in very early phase. It's in a playable phase, though. You can enjoy some matches with friends already :)
> > It's a CMake C++ project, just use an ordinary compile which supports a CMake project.
> > Build from dev branch, there are some notable bugs fixed.
> > I've updated the README file. Would you read it, please?
> 
> thanks a lot. I will have a try. good job~~~

@cgreche I have compiled it successfully, also can connect to the server using the official carom.exe.but it doesn't respond after logging in, have you encountered this phenomenon?

**Comment by cgreche** [comment]
> > > Hello, my friend.
> > > The project is in very early phase. It's in a playable phase, though. You can enjoy some matches with friends already :)
> > > It's a CMake C++ project, just use an ordinary compile which supports a CMake project.
> > > Build from dev branch, there are some notable bugs fixed.
> > > I've updated the README file. Would you read it, please?
> > 
> > 
> > thanks a lot. I will have a try. good job~~~
> 
> @cgreche I have compiled it successfully, also can connect to the server using the official carom.exe.
> 
> but it doesn't any respond after logging in, have you encountered this case?

Hello,

FIrst, let me tell you how Carom3D works as of its last version:
It tries to connect to caromengopening.neoact.com (host you use to redirect to your server IP by changing hosts) on the hardcoded 9882 port. Then it receives a list of arbitrary host/ports where you request the connection to.

In its early stage, Open Carom3D Server handles it very poorly, as it support only one game server and you must provide the IP you want to expose in the server_state.cpp file, be it to the "9882 port server" or the arbitrary host/port server.

Probable causes of your unsuccess:
- You are not exposing the right hostname you are trying to connect. If you are on a lan on different computers it can be a problem;
- Your firewall is blocking connections on the port you are exposing;
- You have a ServerAddress folder inside your Carom3D installation path (it may contain a file named ServerAddress.txt), which causes you to think you are connecting to the right server, while you are not.

Try  one of the things above, and answer me back, please.

Thank you.

**Comment by yanxiyue** [comment]
> > > > Hello, my friend.
> > > > The project is in very early phase. It's in a playable phase, though. You can enjoy some matches with friends already :)
> > > > It's a CMake C++ project, just use an ordinary compile which supports a CMake project.
> > > > Build from dev branch, there are some notable bugs fixed.
> > > > I've updated the README file. Would you read it, please?
> > > 
> > > 
> > > thanks a lot. I will have a try. good job~~~
> > 
> > 
> > @cgreche I have compiled it successfully, also can connect to the server using the official carom.exe.
> > but it doesn't any respond after logging in, have you encountered this case?
> 
> Hello,
> 
> FIrst, let me tell you how Carom3D works as of its last version:
> It tries to connect to caromengopening.neoact.com (host you use to redirect to your server IP by changing hosts) on the hardcoded 9882 port. Then it receives a list of arbitrary host/ports where you request the connection to.
> 
> In its early stage, Open Carom3D Server handles it very poorly, as it support only one game server and you must provide the IP you want to expose in the server_state.cpp file, be it to the "9882 port server" or the arbitrary host/port server.
> 
> Probable causes of your unsuccess:
> 
> * You are not exposing the right hostname you are trying to connect in **server_state.cpp** filename. If you are on a lan on different computers it can be a problem;
> * Your firewall is blocking connections on the port you are exposing;
> * You have a ServerAddress folder inside your Carom3D installation path (it may contain a file named ServerAddress.txt), which causes you to think you are connecting to the right server, while you are not.
> 
> Try one of the things above, and answer me back, please.
> 
> Thank you.

Thank you for such a quick and detailed response. Let me describe more detail：

1. the Carom3D version which I am using is `5.31`
2. the operating system is `windows 10`
3. server and client running on the `same computer`
4. after clicking "online" , can be prompted to enter username and password.
5. after clicking "log in", the console of the server can output a log like 
```
 Carom3d 5.31 log in: user pwd
```
6. but the client doesn't respond and remains on the original page.

**Comment by cgreche** [comment]
Could you tell me the value of HOST macro in the server_starter.cpp? Is it "127.0.0.1"?

Have you checked if there is folder called ServerAddress in your Carom3D installation folder?

If yes, it sounds like a bug in the application. Could you try building the latest version on **dev** branch?

Thank you.

**Comment by yanxiyue** [comment]
It's already working after building the latest version on dev branch. thanks a lot.

**Comment by felipeaav** [comment]
I can't compile.
"C:\open-carom3d-server-master\src\business\service\server_service.h|10|fatal error: business\game_server\game_server.h: No such file or directory|"
